services:
  localstack:
    image: localstack/localstack:4.13.1@sha256:46302bcb91a7e8008e6394be8afafdbfa40fb77a54d4046a38be35992042d5de
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - PERSIST=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,lambda,dynamodb,sqs,sns,iam,cloudformation
    volumes:
      - ./volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 4gb
